### ISSUE TITLE
ローカルのテストが通らない

### ISSUE THREAD

**Issue by kazweda** [kazweda/laravel-12-livewire-workos#5]
```sh
sail artisan test

Tests:    7 passed (11 assertions)
```

**Comment by kazweda** [comment]
### .github/workflows/tests.yml
key:generate のあとをsailの他のプロジェクトを参考に手直し。
```yml
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          npm install
          npm run build
          php artisan test
```
